package main

// backlog.go — the exhaustive, generated half of docs/BACKLOG.md.
//
// The BACKLOG is the single file we read to tackle every open issue in the
// compiler. Its top half is hand-authored (the prioritised, high-leverage
// narrative); everything below the marker is generated here from the SAME
// docs/status/data/*.json the status pages render from, so it can never drift
// into a stale hand-copied changelog.
//
// EVERY caveat is an issue to tackle — a missing feature and a behavioural
// divergence from Node/TS/JS both break code someone ports to this compiler, so
// no caveat is "just documentation". Strict Coverage per area = the ✅ features
// with ZERO caveats; the only way to raise it is to delete a caveat by actually
// fixing it. This section is the burn-down: it shrinks only when real work
// lands, never by reformatting.

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// generateBacklogFile is the full docs/BACKLOG.md: the hand-authored priority
// narrative (everything up to backlogMarker in the committed file, kept
// verbatim) followed by the freshly generated caveat index. On the first run
// (no marker yet) the whole committed file is treated as the preamble.
func generateBacklogFile(areas map[string]*StatusArea) (string, error) {
	raw, err := os.ReadFile("docs/BACKLOG.md")
	if err != nil {
		return "", err
	}
	text := string(raw)
	preamble := text
	if i := strings.Index(text, backlogMarker); i >= 0 {
		preamble = text[:i]
	}
	preamble = strings.TrimRight(preamble, "\n") + "\n\n"
	return preamble + generateBacklogIndex(areas), nil
}

// backlogMarker separates the hand-authored priority narrative (above) from the
// generated caveat index (below). generateAll keeps everything up to and
// including this line verbatim and regenerates the rest.
const backlogMarker = "<!-- STATUS-CAVEATS:BEGIN — generated by `make status` from docs/status/data/*.json; do not edit below this line -->"

// caveatCount sums the caveats across an area's parity-counted tables.
func caveatCount(a *StatusArea) int {
	n := 0
	for _, seg := range a.Segments {
		if seg.Table == nil {
			continue
		}
		for _, r := range seg.Table.Rows {
			n += len(r.Caveats)
		}
	}
	return n
}

// backlogPathFix rewrites doc links that are relative to docs/status/*.md so
// they resolve from docs/BACKLOG.md (one directory up).
func backlogPathFix(s string) string {
	s = strings.ReplaceAll(s, "](../adr/", "](adr/")
	s = strings.ReplaceAll(s, "](../tdd/", "](tdd/")
	return s
}

// generateBacklogIndex renders the generated caveat index (the text that goes
// below backlogMarker). Areas are ordered worst-Strict-Coverage first, so the
// biggest debt surfaces at the top; every caveat is listed under its feature.
func generateBacklogIndex(areas map[string]*StatusArea) string {
	type areaStat struct {
		area                   *StatusArea
		impl, strict, total, c int
	}
	var stats []areaStat
	totalCav, totImpl, totStrict, totTot := 0, 0, 0, 0
	for _, a := range areas {
		impl, strict, total := countArea(a)
		c := caveatCount(a)
		totalCav += c
		totImpl, totStrict, totTot = totImpl+impl, totStrict+strict, totTot+total
		if c == 0 {
			continue // area is caveat-clean — nothing to tackle here
		}
		stats = append(stats, areaStat{a, impl, strict, total, c})
	}
	// Worst strict coverage first; tie-break more caveats first, then title.
	sort.SliceStable(stats, func(i, j int) bool {
		pi, pj := pctFloat(stats[i].strict, stats[i].total), pctFloat(stats[j].strict, stats[j].total)
		if pi != pj {
			return pi < pj
		}
		if stats[i].c != stats[j].c {
			return stats[i].c > stats[j].c
		}
		return stats[i].area.Title < stats[j].area.Title
	})

	var b strings.Builder
	b.WriteString(backlogMarker + "\n\n")
	b.WriteString("## Every open issue — the full caveat index\n\n")
	b.WriteString("Generated by `make status` from `docs/status/data/*.json`. **Every line here is an issue to tackle.** ")
	b.WriteString("A missing feature and a behavioural divergence both break code ported from Node/TS/JS, so both count. ")
	b.WriteString("**Strict Coverage** of an area = the ✅ features carrying zero caveats; the number rises only when a caveat is *fixed and deleted*, never by rewording. Fix a caveat in the status data and it disappears from here; do not edit below the marker by hand.\n\n")
	b.WriteString(fmt.Sprintf("**Total: %d caveats · overall Strict Coverage %d/%d (%s).** Areas below are ordered worst Strict Coverage first.\n",
		totalCav, totStrict, totTot, fmtPct(totStrict, totTot)))

	for _, s := range stats {
		heat := fmt.Sprintf("Strict %d/%d (%s)", s.strict, s.total, fmtPct(s.strict, s.total))
		if s.total == 0 {
			// A completeness-index table (not parity-counted) has no Strict
			// fraction — its caveats are still real issues to tackle.
			heat = "completeness index (not parity-counted)"
		}
		b.WriteString(fmt.Sprintf("\n### %s — %s · %d caveat%s — [%s](status/%s)\n",
			s.area.Title, heat, s.c, plural(s.c), s.area.Title, s.area.File))
		for _, seg := range s.area.Segments {
			if seg.Table == nil {
				continue
			}
			for _, r := range seg.Table.Rows {
				for _, cav := range r.Caveats {
					b.WriteString(fmt.Sprintf("- %s — %s\n", r.Feature, backlogPathFix(cav)))
				}
			}
		}
	}
	return b.String()
}

func pctFloat(n, d int) float64 {
	if d == 0 {
		return 100
	}
	return float64(n) / float64(d)
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
