package main

// rollup.go — a machine-readable projection of the README index's per-area
// Coverage/Strict cells and per-section totals, emitted as
// docs/status/coverage-rollup.json. It exists so downstream consumers (the
// website's landing "what actually works" figures and the /docs/coverage bars)
// can source exact numbers from data instead of hand-copying them — the same
// "data is the source, projections are generated" discipline the status pages
// and the conformance summary already follow.
//
// Every number here is computed by the SAME countTable/roundPct/sumCategoryTable
// used to render the README, so the rollup can never disagree with the page.
// It is written by `make status` and diff-checked by `make status-check`.

import (
	"encoding/json"
	"strings"
)

const coverageRollupFile = "coverage-rollup.json"

type rollupFrac struct {
	Impl  int `json:"impl"`
	Total int `json:"total"`
	Pct   int `json:"pct"`
}

type rollupRow struct {
	Category string      `json:"category"`
	PageFile string      `json:"pageFile,omitempty"`
	Coverage *rollupFrac `json:"coverage,omitempty"` // nil for non-fraction cells (index rows, mode lists)
	Strict   *rollupFrac `json:"strict,omitempty"`   // nil when the page has no Caveats column and no fractional override
	Caveats  string      `json:"caveats,omitempty"`
}

type rollupSection struct {
	Section string      `json:"section"`
	Total   *rollupFrac `json:"total,omitempty"`
	Rows    []rollupRow `json:"rows"`
}

type coverageRollup struct {
	Note          string          `json:"_note"`
	SchemaVersion int             `json:"schemaVersion"`
	Sections      []rollupSection `json:"sections"`
}

// fracFromCell parses a "n/d, p%" README cell into numbers, or reports false for
// a non-fraction cell ("— index", "3/3 modes (`manual`…)", "✅ 2 modes").
func fracFromCell(cell string) (rollupFrac, bool) {
	m := fracCellRe.FindStringSubmatch(cell)
	if m == nil {
		return rollupFrac{}, false
	}
	return rollupFrac{Impl: atoi(m[1]), Total: atoi(m[2]), Pct: atoi(m[4])}, true
}

// generateCoverageRollup builds the rollup from the same index model the README
// renders from: it walks the index segments, tracking the current "## Section"
// heading, and for each category row derives the exact Coverage/Strict cells.
func generateCoverageRollup(idx *StatusIndex, areas map[string]*StatusArea) (string, error) {
	doc := coverageRollup{
		Note:          "GENERATED by statusgen from docs/status/data/*.json — do not edit. Run `make status`; `make status-check` fails on drift.",
		SchemaVersion: 1,
	}
	section := ""
	for si := range idx.Segments {
		s := idx.Segments[si]
		switch s.Kind {
		case "block":
			// A lone "## Heading" block opens a new section.
			if strings.HasPrefix(s.Text, "## ") && !strings.Contains(s.Text, "\n") {
				section = strings.TrimPrefix(s.Text, "## ")
			}
		case "categoryTable":
			sec := rollupSection{Section: section}
			if n, d := sumCategoryTable(&idx.Segments[si], areas); d > 0 {
				sec.Total = &rollupFrac{Impl: n, Total: d, Pct: roundPct(n, d)}
			}
			for _, r := range s.Rows {
				row := rollupRow{Category: r.Category, PageFile: r.PageFile, Caveats: r.Caveats}
				var tbl *Table
				if r.PageFile != "" {
					if area, ok := areas[r.PageFile]; ok {
						if t, err := resolveCategoryTableRef(area, r.Category); err == nil {
							tbl = t
						}
					}
				}
				// Coverage: derived when a table backs it and there's no
				// authored override; otherwise parse a fractional override.
				if r.CoverageOverride == "" && tbl != nil {
					impl, _, total := countTable(tbl)
					row.Coverage = &rollupFrac{Impl: impl, Total: total, Pct: roundPct(impl, total)}
				} else if f, ok := fracFromCell(r.CoverageOverride); ok {
					row.Coverage = &f
				}
				// Strict: derived only when the backing table has a Caveats
				// column; otherwise parse a fractional override (e.g. Desktop's
				// authored 0/20).
				if r.StrictOverride == "" && tbl != nil && tbl.HasCaveats {
					_, strict, total := countTable(tbl)
					row.Strict = &rollupFrac{Impl: strict, Total: total, Pct: roundPct(strict, total)}
				} else if f, ok := fracFromCell(r.StrictOverride); ok {
					row.Strict = &f
				}
				sec.Rows = append(sec.Rows, row)
			}
			doc.Sections = append(doc.Sections, sec)
		}
	}

	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
