// Command libconform diffs the builtin declarations (lib/*.d.ts, TDD-00230
// P3.1) against TypeScript's own library declarations (.ts-tests/src/lib,
// fetched by tools/conformance/fetch.sh at the pinned version); see package
// lib/conform. It exits non-zero when anything is reported that allow.txt
// (one "Interface.member" or "name" per line) does not list.
//
// With -globals FILE it instead writes every global name TypeScript's
// library and Node's declarations (.types-node) declare, one per line: the
// list the checker's TS2304 consults (lib/tsglobals.txt).
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"KlainMainLang/lib/conform"
)

func main() {
	tsLib := flag.String("tslib", ".ts-tests/src/lib", "TypeScript's library declarations")
	allowFile := flag.String("allow", "tools/libconform/allow.txt", "allowlisted divergences")
	typesNode := flag.String("typesnode", ".types-node", "Node's type declarations (@types/node)")
	globals := flag.String("globals", "", "write the global name list here instead of diffing")
	modules := flag.String("modules", "", "write Node's module type-export list here instead of diffing")
	flag.Parse()
	if *modules != "" {
		exports, err := conform.ModuleExports(*typesNode)
		if err != nil {
			fmt.Fprintln(os.Stderr, "libconform:", err)
			os.Exit(2)
		}
		var specs []string
		for spec := range exports {
			specs = append(specs, spec)
		}
		sort.Strings(specs)
		var b strings.Builder
		b.WriteString("# Every type name each of Node's modules exports, per @types/node: \"module name…\".\n# Generated by `go run ./tools/libconform -modules lib/nodemodules.txt`; do not edit.\n")
		for _, spec := range specs {
			b.WriteString(spec + " " + strings.Join(exports[spec], " ") + "\n")
		}
		if err := os.WriteFile(*modules, []byte(b.String()), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "libconform:", err)
			os.Exit(2)
		}
		fmt.Printf("%d modules written to %s\n", len(specs), *modules)
		return
	}
	if *globals != "" {
		names, err := conform.GlobalNames(*tsLib, *typesNode)
		if err != nil {
			fmt.Fprintln(os.Stderr, "libconform:", err)
			os.Exit(2)
		}
		lines := conform.GlobalLines(names)
		header := "# Every global name TypeScript's library and @types/node declare; \"value\"\n# marks a value's. Generated by `go run ./tools/libconform -globals\n# lib/tsglobals.txt`; do not edit.\n"
		if err := os.WriteFile(*globals, []byte(header+strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "libconform:", err)
			os.Exit(2)
		}
		fmt.Printf("%d global names written to %s\n", len(names), *globals)
		return
	}
	allowed := map[string]bool{}
	if f, err := os.Open(*allowFile); err == nil {
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			l := strings.TrimSpace(sc.Text())
			if l != "" && !strings.HasPrefix(l, "#") {
				allowed[strings.Fields(l)[0]] = true
			}
		}
		f.Close()
	}
	problems, review, err := conform.Diff(*tsLib, allowed)
	if err != nil {
		fmt.Fprintln(os.Stderr, "libconform:", err)
		os.Exit(2)
	}
	for _, w := range review {
		fmt.Println("review:", w)
	}
	for _, p := range problems {
		fmt.Println(p)
	}
	fmt.Printf("%d divergences not allowlisted, %d members to review\n", len(problems), len(review))
	if len(problems) > 0 {
		os.Exit(1)
	}
}
