// TypeScript acceptance-oracle track (TDD-00121 Track C). This reverses
// TDD-00082's "the TS suite is terminal, nothing runnable to automate"
// conclusion: that held for a compile-and-run framing, but Microsoft's
// tests/cases corpus ships a baseline per case in tests/baselines/reference/,
// and a case with a `*.errors.txt` baseline is one TypeScript rejects while one
// without compiles clean. That is an accept/reject oracle for a *front-end*
// (parse + resolve + codegen, no clang, no run) pipeline: does this compiler
// reject what TypeScript rejects and accept what it accepts?
//
// V1 measures accept/reject agreement only (not error-message fidelity, and not
// per-error position). Multi-file cases (`// @filename:` directives) and cases
// that lean on ambient lib.d.ts surface this compiler doesn't model are binned
// as out-of-scope rather than counted as disagreements.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// reTSMultiFile detects the `// @filename: x.ts` directive that marks a
// multi-file case — out of scope for the single-entry V1 oracle.
var reTSMultiFile = regexp.MustCompile(`(?mi)^//\s*@filename:`)

type tsResult struct {
	Case   string
	Group  string // compiler | conformance
	Status string // MATCH_ACCEPT | MATCH_REJECT | MISMATCH_FALSE_REJECT | MISMATCH_FALSE_ACCEPT | SKIP_OUT_OF_SCOPE
	Reason string
}

func runTSSuite(workDir string, timeout time.Duration) {
	if err := os.MkdirAll(workDir, 0755); err != nil {
		fatal("creating workdir: %v", err)
	}
	casesRoot := ".ts-tests/tests/cases"
	baselineDir := ".ts-tests/tests/baselines/reference"
	if _, err := os.Stat(casesRoot); err != nil {
		fatal("reading TS corpus %s (run tools/conformance/fetch.sh first): %v", casesRoot, err)
	}

	// Index which case basenames have an errors baseline (⇒ expected-reject).
	hasErrorsBaseline := map[string]bool{}
	if entries, err := os.ReadDir(baselineDir); err == nil {
		for _, e := range entries {
			n := e.Name()
			if strings.HasSuffix(n, ".errors.txt") {
				hasErrorsBaseline[strings.TrimSuffix(n, ".errors.txt")] = true
			}
		}
	}

	var results []tsResult
	for _, group := range []string{"compiler", "conformance"} {
		root := filepath.Join(casesRoot, group)
		_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() || !strings.HasSuffix(p, ".ts") || strings.HasSuffix(p, ".d.ts") {
				return nil
			}
			results = append(results, runOneTS(p, group, hasErrorsBaseline, workDir))
			return nil
		})
	}

	if fl := os.Getenv("TS_FALSEREJECT"); fl != "" {
		var lines []string
		for _, r := range results {
			if r.Status == "MISMATCH_FALSE_REJECT" {
				lines = append(lines, r.Case+"\t"+strings.ReplaceAll(r.Reason, "\n", " "))
			}
		}
		sort.Strings(lines)
		_ = os.WriteFile(fl, []byte(strings.Join(lines, "\n")+"\n"), 0644)
	}

	out := "docs/testing/CONFORMANCE-RESULTS-TS.md"
	if err := writeTSReport(out, results); err != nil {
		fatal("writing TS report: %v", err)
	}
	fmt.Fprintf(os.Stderr, "ts suite: %d cases, report written to %s\n", len(results), out)
}

func runOneTS(path, group string, hasErrorsBaseline map[string]bool, workDir string) (res tsResult) {
	base := strings.TrimSuffix(filepath.Base(path), ".ts")
	res.Case = base
	res.Group = group

	raw, err := os.ReadFile(path)
	if err != nil {
		res.Status = "SKIP_OUT_OF_SCOPE"
		res.Reason = "read error"
		return res
	}
	src := string(raw)
	if reTSMultiFile.MatchString(src) {
		res.Status = "SKIP_OUT_OF_SCOPE"
		res.Reason = "multi-file case (@filename directives)"
		return res
	}

	expectReject := hasErrorsBaseline[base]
	_, cerr := frontEndSource(src, workDir, "ts")
	accepted := cerr == nil

	switch {
	case expectReject && !accepted:
		res.Status = "MATCH_REJECT" // TS rejects, we reject
	case !expectReject && accepted:
		res.Status = "MATCH_ACCEPT" // TS accepts, we accept
	case expectReject && accepted:
		res.Status = "MISMATCH_FALSE_ACCEPT" // TS rejects, we accepted — a real soundness gap
		res.Reason = "expected rejection (TS has an errors baseline) but this compiled clean"
	default: // !expectReject && !accepted
		res.Status = "MISMATCH_FALSE_REJECT" // TS accepts, we rejected — usually an unsupported-feature scope gap
		if cerr != nil {
			res.Reason = normalizeReason("REJECTED", cerr.Error())
		}
	}
	return res
}

func writeTSReport(path string, all []tsResult) error {
	var b strings.Builder
	b.WriteString("# TypeScript acceptance-oracle results\n\n")
	b.WriteString("Generated by `tools/conformance -suite=ts` (TDD-00121 Track C) against Microsoft's `tests/cases/{compiler,conformance}` corpus, using each case's `tests/baselines/reference/*.errors.txt` baseline as an **accept/reject oracle**: a case with an errors baseline should be rejected; one without should compile clean. This measures this compiler's **front-end** (parse + resolve + codegen, no run) against TypeScript's own accept/reject verdict. Regenerate with `make conformance-ts`. Do not hand-edit; re-run instead.\n\n")
	b.WriteString("V1 measures accept/reject **agreement** only — not error-message text or position. A **false-reject** is usually a scope gap (a valid-TS feature this narrow typed subset doesn't implement), and those dominate the disagreements by design; a **false-accept** (TypeScript rejects but this compiler accepts) is the more interesting signal — a soundness gap in what this compiler should have caught. Multi-file cases are skipped as out of scope for this single-entry V1.\n\n")

	var mAcc, mRej, fAcc, fRej, skip int
	byGroup := map[string]*struct{ mAcc, mRej, fAcc, fRej, skip int }{}
	for _, r := range all {
		g, ok := byGroup[r.Group]
		if !ok {
			g = &struct{ mAcc, mRej, fAcc, fRej, skip int }{}
			byGroup[r.Group] = g
		}
		switch r.Status {
		case "MATCH_ACCEPT":
			mAcc++
			g.mAcc++
		case "MATCH_REJECT":
			mRej++
			g.mRej++
		case "MISMATCH_FALSE_ACCEPT":
			fAcc++
			g.fAcc++
		case "MISMATCH_FALSE_REJECT":
			fRej++
			g.fRej++
		default:
			skip++
			g.skip++
		}
	}
	classified := mAcc + mRej + fAcc + fRej
	agree := mAcc + mRej
	pct := 0.0
	if classified > 0 {
		pct = 100 * float64(agree) / float64(classified)
	}
	fmt.Fprintf(&b, "## Overall\n\n**%d / %d agree with TypeScript (%.1f%%)** on accept/reject over %d classified cases (%d multi-file/out-of-scope skipped).\n\n", agree, classified, pct, classified, skip)
	fmt.Fprintf(&b, "- **%d** match-accept (both compile clean)\n- **%d** match-reject (both reject)\n- **%d** false-reject (TS accepts, we reject — usually an unsupported-feature scope gap)\n- **%d** false-accept (TS rejects, we accept — a soundness gap worth investigating)\n\n", mAcc, mRej, fRej, fAcc)

	b.WriteString("## By group\n\n| Group | Agree | Classified | % | False-accept | Skipped |\n|---|---|---|---|---|---|\n")
	groups := make([]string, 0, len(byGroup))
	for g := range byGroup {
		groups = append(groups, g)
	}
	sort.Strings(groups)
	for _, g := range groups {
		s := byGroup[g]
		cl := s.mAcc + s.mRej + s.fAcc + s.fRej
		ag := s.mAcc + s.mRej
		p := 0.0
		if cl > 0 {
			p = 100 * float64(ag) / float64(cl)
		}
		fmt.Fprintf(&b, "| %s | %d | %d | %.1f%% | %d | %d |\n", g, ag, cl, p, s.fAcc, s.skip)
	}

	// The false-accepts are the actionable list — enumerate them (bounded).
	b.WriteString("\n## False-accepts (TypeScript rejects, this compiler accepted)\n\nEach is a case where this compiler compiled clean but TypeScript reports an error — a soundness gap to investigate (some are features TypeScript rejects for reasons outside this compiler's type model, so not all are bugs).\n\n| Case | Group |\n|---|---|\n")
	var fa []tsResult
	for _, r := range all {
		if r.Status == "MISMATCH_FALSE_ACCEPT" {
			fa = append(fa, r)
		}
	}
	sort.Slice(fa, func(i, j int) bool { return fa[i].Case < fa[j].Case })
	limit := 100
	if len(fa) < limit {
		limit = len(fa)
	}
	for _, r := range fa[:limit] {
		fmt.Fprintf(&b, "| `%s` | %s |\n", r.Case, r.Group)
	}
	if len(fa) > limit {
		fmt.Fprintf(&b, "| … | +%d more |\n", len(fa)-limit)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}
