// Package lib holds the builtin surface as declaration files (TDD-00230
// P3.1): the ECMAScript, Node and web APIs this compiler implements, written
// as `.d.ts` declarations that the checker parses and binds like user code.
package lib

import (
	"embed"
	"regexp"
	"sort"
	"strings"
	"sync"

	"KlainMainLang/ast"
	"KlainMainLang/parser"
)

//go:embed *.d.ts
var files embed.FS

// tsGlobals is every global name TypeScript's library and Node's
// declarations declare (generated by tools/libconform -globals).
//
//go:embed tsglobals.txt
var tsGlobals string

// nodeModules is every type name each of Node's modules exports, per
// @types/node (generated by tools/libconform -modules).
//
//go:embed nodemodules.txt
var nodeModules string

var (
	globalsOnce sync.Once
	globals     map[string]bool
	modulesOnce sync.Once
	modules     map[string]map[string]bool
)

// NodeModuleExport reports whether @types/node's module spec (`http`,
// `node:http`) exports name as a type (an interface, class, type alias or
// enum): a name tsc resolves in `import { name } from spec`, whether or not
// this compiler implements it.
func NodeModuleExport(spec, name string) bool {
	modulesOnce.Do(func() {
		modules = map[string]map[string]bool{}
		for _, l := range strings.Split(nodeModules, "\n") {
			f := strings.Fields(l)
			if len(f) == 0 || strings.HasPrefix(f[0], "#") {
				continue
			}
			m := map[string]bool{}
			for _, n := range f[1:] {
				m[n] = true
			}
			modules[f[0]] = m
		}
	})
	return modules[spec][name]
}

// KnownGlobal reports whether TypeScript's library or Node's declarations
// declare name globally: a name tsc resolves, whether or not this compiler
// declares it too.
func KnownGlobal(name string) bool {
	globalsOnce.Do(func() {
		globals = map[string]bool{}
		for _, l := range strings.Split(tsGlobals, "\n") {
			if f := strings.Fields(l); len(f) > 0 && !strings.HasPrefix(f[0], "#") {
				globals[f[0]] = len(f) > 1 && f[1] == "value"
			}
		}
	})
	_, ok := globals[name]
	return ok
}

// GlobalValue reports whether TypeScript's library or Node's declarations
// declare name as a global value (a variable, function, class, enum or
// namespace), not only as a type.
func GlobalValue(name string) bool {
	KnownGlobal("") // load the table
	return globals[name]
}

var (
	once  sync.Once
	progs []*ast.Program
	err   error
)

// Programs returns every declaration file, parsed, in file-name order. They
// are parsed once per process; the result is shared and must not be
// modified.
func Programs() ([]*ast.Program, error) {
	once.Do(func() {
		entries, e := files.ReadDir(".")
		if e != nil {
			err = e
			return
		}
		var names []string
		for _, en := range entries {
			names = append(names, en.Name())
		}
		sort.Strings(names)
		for _, name := range names {
			src, e := files.ReadFile(name)
			if e != nil {
				err = e
				return
			}
			p, e := parser.ParseLibrary(string(src))
			if e != nil {
				err = e
				return
			}
			progs = append(progs, p)
		}
	})
	return progs, err
}

// NodeTypeName reports whether some Node module exports name as a type: one
// an erased builtin import may have bound (`import { IncomingMessage }`). A
// name a module written in TypeScript exports is bound by its import, so a
// bare use of it is unresolved, as tsc has it.
func NodeTypeName(name string) bool {
	NodeModuleExport("", "") // load the table
	if tsModuleTypeNames()[name] {
		return false
	}
	for _, m := range modules {
		if m[name] {
			return true
		}
	}
	return false
}

// AnyGlobal reports whether some global name KnownGlobal accepts satisfies f.
func AnyGlobal(f func(string) bool) bool {
	KnownGlobal("") // load the table
	for n := range globals {
		if f(n) {
			return true
		}
	}
	return false
}

// GlobalNames returns every global name KnownGlobal accepts, sorted, each
// with whether it is a value's (GlobalValue).
func GlobalNames() (names []string, values []bool) {
	KnownGlobal("") // load the table
	for n := range globals {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		values = append(values, globals[n])
	}
	return names, values
}

// The builtin modules written in TypeScript (TDD-00231): `node/stream.ts`
// is `stream` (and `node:stream`), `node/stream_promises.ts` is
// `stream/promises`. They are compiled with the program that imports them.
//
//go:embed node
var nodeModuleFiles embed.FS

// ModuleRoot is the pseudo-directory a builtin TypeScript module's path
// names; no file on disk has it.
const ModuleRoot = "/__kml_lib/node/"

// ModulePath is the pseudo-path of the builtin module spec written in
// TypeScript, or false when spec names none.
func ModulePath(spec string) (string, bool) {
	name := strings.TrimPrefix(spec, "node:")
	if name == "" || strings.Contains(name, ".") || strings.HasPrefix(name, "internal") {
		return "", false
	}
	// `klain:ws` is klain_ws.ts, `stream/promises` stream_promises.ts.
	file := strings.NewReplacer("/", "_", ":", "_").Replace(name) + ".ts"
	if _, err := nodeModuleFiles.Open("node/" + file); err != nil {
		return "", false
	}
	return ModuleRoot + file, true
}

// CompanionPath is the pseudo-path of the part written in TypeScript of the
// builtin module spec whose other members codegen implements (`fs`'s
// streams and callback operations are `node/internal_fs.ts`), or false when
// it has none. A program importing the module imports its companion too.
func CompanionPath(spec string) (string, bool) {
	name := strings.TrimPrefix(spec, "node:")
	if name == "" || strings.Contains(name, ".") {
		return "", false
	}
	file := "internal_" + strings.ReplaceAll(name, "/", "_") + ".ts"
	if _, err := nodeModuleFiles.Open("node/" + file); err != nil {
		return "", false
	}
	return ModuleRoot + file, true
}

// ModuleSource is the source of the builtin module at path (a ModulePath
// result), or false when path is not one.
func ModuleSource(path string) ([]byte, bool) {
	if !strings.HasPrefix(path, ModuleRoot) {
		return nil, false
	}
	src, err := nodeModuleFiles.ReadFile("node/" + strings.TrimPrefix(path, ModuleRoot))
	if err != nil {
		return nil, false
	}
	return src, true
}

// DefaultIsNamespace reports whether the builtin module at path reads a
// default import as its namespace (`import stream from 'stream'`, whose
// `stream.Readable` is the module's own export, as Node's default export
// carries them).
func DefaultIsNamespace(path string) bool {
	src, ok := ModuleSource(path)
	return ok && strings.Contains(string(src), "kml:default-namespace")
}

var (
	tsTypeNamesOnce sync.Once
	tsTypeNames     map[string]bool
)

var exportedTypeDecl = regexp.MustCompile(`(?m)^export (?:declare )?(?:abstract )?(?:class|interface|type) ([A-Za-z_$][A-Za-z0-9_$]*)`)

// tsModuleTypeNames is every class, interface and type alias the builtin
// modules written in TypeScript export.
func tsModuleTypeNames() map[string]bool {
	tsTypeNamesOnce.Do(func() {
		tsTypeNames = map[string]bool{}
		entries, _ := nodeModuleFiles.ReadDir("node")
		for _, en := range entries {
			if !strings.HasSuffix(en.Name(), ".ts") {
				continue
			}
			src, err := nodeModuleFiles.ReadFile("node/" + en.Name())
			if err != nil {
				continue
			}
			for _, m := range exportedTypeDecl.FindAllStringSubmatch(string(src), -1) {
				tsTypeNames[m[1]] = true
			}
		}
	})
	return tsTypeNames
}
