package llvm

import (
	"fmt"
	"strings"
)

// webview_dts.go — TDD-00142 Stage 6: generate a `declare global { interface
// Window { … } }` .d.ts from the program's typed webview bindings, so page-side
// code gets autocomplete/typechecking on the injected `window.*` functions. The
// generated file doubles as a machine-checkable record of the exact
// frontend↔backend contract — the audit surface for the bindings allowlist.

// webviewBindingSig is one typed `window.*` binding recorded at bind time (with
// a compile-time-known name). Ret is nil for a void return.
type webviewBindingSig struct {
	Name   string
	Params []Type
	Ret    *Type
}

// HasWindowBindings reports whether any typed binding was recorded (so the CLI
// can warn on --emit-window-dts for a program that has none).
func (e *Emitter) HasWindowBindings() bool { return len(e.webviewBindings) > 0 }

// WindowDTS renders the `declare global { interface Window { … } }` for every
// typed binding. A bound `window.name(...)` returns a Promise page-side, so a
// sync callback returning R declares `Promise<R>` and an async callback
// (returning Promise<R>) declares `Promise<R>` too (unwrapped once).
func (e *Emitter) WindowDTS() string {
	var b strings.Builder
	b.WriteString("// Generated by klainmain --emit-window-dts.\n")
	b.WriteString("// The window.* functions exposed by this program's Webview bindings.\n\n")
	b.WriteString("export {}\n\ndeclare global {\n  interface Window {\n")
	for _, s := range e.webviewBindings {
		params := make([]string, len(s.Params))
		for i, p := range s.Params {
			params[i] = fmt.Sprintf("arg%d: %s", i, tsTypeString(p))
		}
		ret := "unknown"
		if s.Ret != nil {
			if s.Ret.IsPromise {
				// async callback: the page promise resolves the inner type.
				if s.Ret.PromiseType != nil {
					ret = tsTypeString(*s.Ret.PromiseType)
				} else {
					ret = "void"
				}
			} else {
				ret = tsTypeString(*s.Ret)
			}
		} else {
			ret = "void"
		}
		b.WriteString(fmt.Sprintf("    %s(%s): Promise<%s>\n", s.Name, strings.Join(params, ", "), ret))
	}
	b.WriteString("  }\n}\n")
	return b.String()
}

// tsTypeString maps a compiler Type back to a TypeScript type string for the
// generated .d.ts. Covers the types typed bind can marshal; anything else is
// `unknown` (honest rather than wrong).
func tsTypeString(ty Type) string {
	switch {
	case ty.IR == "void" || ty.IR == "":
		return "void"
	case ty.IR == "i1":
		return "boolean"
	case ty.Float:
		return "number"
	case ty.IsArray && ty.ElemType != nil:
		return tsTypeString(*ty.ElemType) + "[]"
	case ty.IsTuple:
		parts := make([]string, len(ty.Fields))
		for i, f := range ty.Fields {
			parts[i] = tsTypeString(f.Ty)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case ty.IsObject:
		parts := make([]string, len(ty.Fields))
		for i, f := range ty.Fields {
			parts[i] = fmt.Sprintf("%s: %s", f.Name, tsTypeString(f.Ty))
		}
		return "{ " + strings.Join(parts, "; ") + " }"
	case ty.IsPromise:
		if ty.PromiseType != nil {
			return "Promise<" + tsTypeString(*ty.PromiseType) + ">"
		}
		return "Promise<void>"
	case isStringTy(ty):
		return "string"
	case ty.IR == "ptr":
		return "unknown"
	default: // integer scalars
		return "number"
	}
}
