// Generates lib/node/internal_encoding_tables.ts from the running Node's own
// encoding label table (lib/internal/encoding.js) and its ICU single-byte
// decoders: node tools/encodingtables/gen.cjs > lib/node/internal_encoding_tables.ts
const src = process.binding('natives')['internal/encoding'];
const i = src.indexOf('const encodings = new SafeMap([');
const j = src.indexOf(']);', i);
const body = src.slice(i, j);
const pairs = [...body.matchAll(/\['([^']+)', '([^']+)'\]/g)].map(m => [m[1], m[2]]);
const names = [...new Set(pairs.map(p => p[1]))];
const single = [];
for (const n of names) {
  if (['utf-8', 'utf-16le', 'utf-16be', 'replacement', 'x-user-defined', 'gbk', 'gb18030', 'big5', 'euc-jp', 'euc-kr', 'iso-2022-jp', 'shift_jis'].includes(n)) continue;
  // a single-byte encoding decodes every byte to one code point (or rejects it)
  let ok = true; const table = [];
  try {
    const d = new TextDecoder(n), f = new TextDecoder(n, { fatal: true });
    for (let b = 0; b < 0x80; b++) if (d.decode(new Uint8Array([b])).codePointAt(0) !== b) ok = false;
    for (let b = 0x80; b < 0x100; b++) {
      let cp;
      try { const s = f.decode(new Uint8Array([b])); cp = [...s].length === 1 ? s.codePointAt(0) : null; } catch { cp = -1; }
      if (cp === null) { ok = false; break; }
      table.push(cp);
    }
  } catch { ok = false; }
  if (ok && table.length === 128) single.push([n, table]);
}
let out = '// Generated by tools/encodingtables/gen.cjs from Node v' + process.versions.node + "'s lib/internal/encoding.js\n// label table and its";
out += " ICU single-byte decoders; do not edit. Each table is the code points\n// of bytes 0x80-0xFF (-1: not mapped).\n\n";
out += 'export const kEncodingLabels: { [label: string]: string } = {\n';
for (const [l, n] of pairs) out += '    ' + JSON.stringify(l) + ': ' + JSON.stringify(n) + ',\n';
out += '};\n\n';
out += 'export const kSingleByte: { [name: string]: number[] } = {\n';
for (const [n, t] of single) {
  out += '    ' + JSON.stringify(n) + ': [\n';
  for (let k = 0; k < 128; k += 16) out += '        ' + t.slice(k, k + 16).map(x => x < 0 ? '-1' : '0x' + x.toString(16)).join(', ') + ',\n';
  out += '    ],\n';
}
out += '};\n';
process.stdout.write(out);
console.error('labels', pairs.length, 'names', names.length, 'single-byte', single.length, single.map(s => s[0]).join(' '));
console.error('multi', names.filter(n => !single.find(s => s[0] === n)).join(' '));
