#!/usr/bin/env python3
"""Generate codegen/llvm/casemapsrc/casemap_tables.h — the Unicode full case
mapping String.prototype.toUpperCase/toLowerCase use (ECMA-262 §22.1.3.29:
the Unicode Default Case Conversion, i.e. UnicodeData simple mappings plus the
unconditional SpecialCasing entries, plus the one language-independent
conditional mapping, Final_Sigma).

Python's str.upper()/str.lower() implement exactly that algorithm from the
interpreter's own Unicode database, so the tables are read off it rather than
from vendored UnicodeData.txt/SpecialCasing.txt. The Unicode version stamped
into the header is the interpreter's (unicodedata.unidata_version); regenerate
with a newer Python to pick up new scripts.

    py tools/gencasemap/gencasemap.py > codegen/llvm/casemapsrc/casemap_tables.h

Three tables come out:
  kml_case_ranges   runs of code points whose upper/lower are single code points
                    at a constant delta (binary-searched; identity runs omitted)
  kml_case_special  code points with a multi-code-point upper or lower
                    (ß → SS, İ → i̇, ﬁ → FI, ᾀ → ἈΙ …), each with both mappings
  kml_cased / kml_case_ignorable  ranges for the Final_Sigma context test
                    (Cased = Lowercase ∪ Uppercase ∪ Lt; Case_Ignorable =
                    Mn ∪ Me ∪ Cf ∪ Lm ∪ Sk ∪ Word_Break{MidLetter,MidNumLet,
                    Single_Quote})
"""
import sys
import unicodedata

MAX = 0x110000

def cps(s):
    return [ord(c) for c in s]

def is_cased(cp):
    c = chr(cp)
    return c.isupper() or c.islower() or unicodedata.category(c) == "Lt"

MID = {0x27, 0x2E, 0x3A, 0xB7, 0x387, 0x5F4, 0x2018, 0x2019, 0x2024, 0x2027,
       0xFE13, 0xFE52, 0xFE55, 0xFF07, 0xFF0E, 0xFF1A}

def is_case_ignorable(cp):
    if cp in MID:
        return True
    return unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf", "Lm", "Sk")

def ranges(pred):
    out = []
    start = None
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            v = False
        else:
            v = pred(cp)
        if v and start is None:
            start = cp
        elif not v and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out

simple = []   # (lo, hi, du, dl)
special = []  # (cp, up[], lo[])
run = None    # [lo, hi, du, dl]
for cp in range(MAX):
    if 0xD800 <= cp <= 0xDFFF:
        up = lo = [cp]
    else:
        c = chr(cp)
        up, lo = cps(c.upper()), cps(c.lower())
    if len(up) != 1 or len(lo) != 1:
        special.append((cp, up, lo))
        if run:
            simple.append(tuple(run)); run = None
        continue
    du, dl = up[0] - cp, lo[0] - cp
    if du == 0 and dl == 0:
        if run:
            simple.append(tuple(run)); run = None
        continue
    if run and run[1] == cp - 1 and run[2] == du and run[3] == dl:
        run[1] = cp
    else:
        if run:
            simple.append(tuple(run))
        run = [cp, cp, du, dl]
if run:
    simple.append(tuple(run))

sys.stdout.reconfigure(newline="\n")  # LF on every host, Windows included
w = sys.stdout.write
w("/* Generated by tools/gencasemap/gencasemap.py - DO NOT EDIT.\n")
w("   Unicode %s (the generating Python's unicodedata). */\n" % unicodedata.unidata_version)
w("#define KML_CASEMAP_UNICODE_VERSION \"%s\"\n\n" % unicodedata.unidata_version)

w("typedef struct { unsigned int lo, hi; int du, dl; } KmlCaseRange;\n")
w("static const KmlCaseRange kml_case_ranges[] = {\n")
for lo, hi, du, dl in simple:
    w("  {0x%04X, 0x%04X, %d, %d},\n" % (lo, hi, du, dl))
w("};\n#define KML_CASE_RANGES_N %d\n\n" % len(simple))

w("typedef struct { unsigned int cp; unsigned char nu, nl; unsigned int up[3], lo[3]; } KmlCaseSpecial;\n")
w("static const KmlCaseSpecial kml_case_special[] = {\n")
for cp, up, lo in special:
    assert len(up) <= 3 and len(lo) <= 3
    u = up + [0] * (3 - len(up))
    l = lo + [0] * (3 - len(lo))
    w("  {0x%04X, %d, %d, {0x%04X, 0x%04X, 0x%04X}, {0x%04X, 0x%04X, 0x%04X}},\n"
      % (cp, len(up), len(lo), u[0], u[1], u[2], l[0], l[1], l[2]))
w("};\n#define KML_CASE_SPECIAL_N %d\n\n" % len(special))

w("typedef struct { unsigned int lo, hi; } KmlCpRange;\n")
for name, pred in (("kml_cased", is_cased), ("kml_case_ignorable", is_case_ignorable)):
    rs = ranges(pred)
    w("static const KmlCpRange %s[] = {\n" % name)
    for lo, hi in rs:
        w("  {0x%04X, 0x%04X},\n" % (lo, hi))
    w("};\n#define %s_N %d\n\n" % (name.upper(), len(rs)))
